extends Text

func _ready() -> void:
	add_date("03/06/2025")
	add_text("7:13 pm", false, "Cal u good? It’s 7:10 already")
	add_text("7:13 pm", true,  "Ahhhhh, hit a traffic jam… and we ran out of gas (tears emoji)😓")
	add_text("7:13 pm", false, "For real? Do you need help? I can drive over and pick you guys up.")
	add_text("7:13 pm", true,  "nooo we r good, should be there in 10 mins")
	add_text("7:13 pm", false, "you sure?")
	add_text("7:13 pm", true,  "trust me BRO")
	
	add_date("03/06/2025")
	add_text("10:29 pm", false, "Made it home safe?")
	add_text("10:29 pm", true,  "Yeah, sooo tired, but it was really nice to see mom and dad for a bit")
	add_text("10:29 pm", false, "wow Cal that’s definitely A BIT")
	add_text("10:29 pm", true,  "lol just been busy with all this law stuff")
	add_text("10:29 pm", false, "Hey just wanted to check you good? I kinda feel like Beth was acting a little weird… Maybe I’m just overthinking it.")
	add_text("10:29 pm", true,  "Nah, we r good. Beth is good. She’s just been overworking lately… ")
	add_text("10:29 pm", false, "ahhhh that makes sense Glad to hear that lol")
	add_text("10:29 pm", true,  "poor detective (emoji)")
	add_text("10:29 pm", false, "ehhhhh Cal, about the thing dad mentioned, just don’t let it bother you")
	add_text("10:29 pm", true,  "right… i just don’t understand what he meant, like..")
	add_text("10:29 pm", true,  "idk, like why did he mentioned the trial 8 years ago all of sudden?")
	add_text("10:29 pm", false, "Look probably we should talk…in person. I’ll stay at the usual place in Abonddi’s tonight.")
	add_text("10:29 pm", false, "idk if you can’t sleep, i’m always there. Or sometime tomorrow if you want")
	add_text("10:29 pm", true,  "Stupid nightshift…")
	add_text("10:29 pm", true,  "Ahhhh anyway Beth needs me right now, catch you later!")

	add_date("03/06/2025")
	add_text("11:31 pm", false, "is Beth alright?")
	add_text("11:31 pm", true,  "oh yea damn she’s just allergic to cuttlefish...")
	add_text("11:31 pm", false, "what? the seppioline con piselli？")
	add_text("11:31 pm", true,  "nvm she’s alright now. still on the night shift? I’m driving over now!")
	add_text("11:31 pm", true,  "Btw which Abbondi’s?")
	add_text("11:31 pm", false, "Cal the old one of course. You know i hate the design of our new branch")
	add_text("11:31 pm", true,  "the 30310 one?")
	add_text("11:31 pm", false, "stop trolling! You know the zip code")
	add_text("11:31 pm", true,  "all good! omw")
